name: Mirror

on:
  push:
    branches:
  pull_request:
    branches:

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-OOP-400-BDX-4-1-raytracer-nolann.dubos.git"
  EXECUTABLES: "raytracer"

jobs:
  check_compilation:
    name: Check compilation
    runs-on: ubuntu-latest
    container: 
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure with CMake
        run: cmake -B .build

      - name: Build project
        run: cmake --build .build

  push_to_mirror:
    if: github.repository != 'EpitechPromo2028/B-OOP-400-BDX-4-1-raytracer-nolann.dubos.git' && github.ref_name == 'main'
    name: Push to Mirror Repository
    runs-on: ubuntu-latest
    container: 
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          target_repo_url: ${{ env.MIRROR_URL }}
